In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split
import torch
from sklearn.preprocessing import MinMaxScaler
from collections import Counter

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main
path = '/content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main'
os.chdir(path)

train_data_path = "/content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main/Data/ECG5000/ECG5000_TRAIN.tsv"
train_data = np.loadtxt(train_data_path)

# Extract features (x) and labels (y)
train_y = train_data[:, 0].astype(int) - 1
train_X = train_data[:, 1:]

test_data_path = "/content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main/Data/ECG5000/ECG5000_TEST.tsv"
test_data = np.loadtxt(test_data_path)

# Extract features (x) and labels (y)
test_y = test_data[:, 0].astype(int) - 1
test_X = test_data[:, 1:]

scaler = MinMaxScaler()
train_X = scaler.fit_transform(train_X)
print("train_X: ", train_X)

scaler = MinMaxScaler()
test_X = scaler.fit_transform(test_X)

# Add Gaussian noise to the data
mean = 0
std = 1.5  # You can adjust the standard deviation based on the level of noise you want

# Add noise to training data
noise = np.random.normal(mean, std, train_X.shape)
train_X_noisy = train_X + noise
print("noisy: ", train_X_noisy)

# Add noise to test data
noise = np.random.normal(mean, std, test_X.shape)
test_X_noisy = test_X + noise

output_dir = "/content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main/TSTCC/data/ECG5000noise"
os.makedirs(output_dir, exist_ok=True)

X_train = train_X_noisy
y_train = train_y

X_val, X_test, y_val, y_test = train_test_split(test_X_noisy, test_y, test_size=0.5, random_state=42)

# Count occurrences of each value in array of non-negative ints
label_counts = np.bincount(test_y)

# Print the counts
for label, count in enumerate(label_counts):
    print(f"Label {label + 1}: {count} occurrences")

dat_dict = dict()
dat_dict["samples"] = torch.from_numpy(X_train).unsqueeze(1)
dat_dict["labels"] = torch.from_numpy(y_train)
torch.save(dat_dict, os.path.join(output_dir, "train.pt"))

dat_dict = dict()
dat_dict["samples"] = torch.from_numpy(X_val).unsqueeze(1)
dat_dict["labels"] = torch.from_numpy(y_val)
torch.save(dat_dict, os.path.join(output_dir, "val.pt"))

dat_dict = dict()
dat_dict["samples"] = torch.from_numpy(X_test).unsqueeze(1)
dat_dict["labels"] = torch.from_numpy(y_test)
torch.save(dat_dict, os.path.join(output_dir, "test.pt"))
print("finished")

Mounted at /content/drive
/content/drive/MyDrive/FYP_Nur_Time_Series_Representation_using_CL-main
train_X:  [[0.46201309 0.31787226 0.19937641 ... 0.67115996 0.79776384 0.69238772]
 [0.33452154 0.15554603 0.12300494 ... 0.75703392 0.82137986 0.50407044]
 [0.40337698 0.35031341 0.18440888 ... 0.69725872 0.79520464 0.62131641]
 ...
 [0.47369449 0.5836108  0.478422   ... 0.84555805 0.85938308 0.83846256]
 [0.51367925 0.55785455 0.3893776  ... 0.66144769 0.68664723 0.6606424 ]
 [0.33029106 0.3351179  0.29677796 ... 0.64022805 0.68554661 0.65589166]]
noisy:  [[ 0.07083134 -1.12987648  1.68360517 ...  0.58945918 -0.42829108
  -1.71283307]
 [-0.31102898 -0.24329125  0.19730628 ...  1.63029618 -0.03817048
   0.93737558]
 [ 0.98151723  1.2101919   2.55789059 ...  0.41000714 -0.47659601
   1.26043785]
 ...
 [-0.28634979 -3.23013819 -0.92579727 ...  0.55453176  0.8615485
   1.74547503]
 [ 2.88082517  0.79899763 -0.0335869  ...  2.52533307  0.59774745
   1.86817682]
 [ 0.06423687 -0.69498335 -3.10

In [ ]:
from google.colab import runtime
runtime.unassign()